import {makeStyles} from '@material-ui/core/styles';

export default makeStyles((theme)=>({
    root:{
        display:"flex",
        justifyContent:"center",
        flexDirection:"column",
    },
    card:{
        padding:"10px",
        display:"flex",
        alignItems:"center",
        flexDirection:"column",
        backgroundColor:"transparent",
    },
    div:{
        display:"flex",
        alignItems:"center",
        flexDirection:"column",
        position:"relative",
    },
    img:{
        height:"200px",
        width:"90%",
        color: '#fff',
        paddingLeft:'0',
        backgroundColor:'#14a31a',
        borderRadius:'25px',
        backgroundImage:'https://app.alvoraplay.com/assets/subgraphic-desktop-footer-left.png',
    },
    textbox:{
        position: "absolute",
        bottom:"65.0%",
        left: "6.00%",
        backgroundColor:'transparent',
        opacity:"0.8",
        color:"white",
        paddingLeft: "12px",
        paddingRight: "18px",
        width:"200px",
        borderRadius:'22px',
    },
    textbox1:{
        position: "absolute",
        bottom:"65.0%",
        left: "75.00%",
        backgroundColor:'transparent',
        opacity:"0.8",
        color:"white",
        paddingLeft: "12px",
        paddingRight: "18px",
        width:"200px",
        borderRadius:'22px',
    },
    textbox2:{
        position: "absolute",
        bottom:"5.0%",
        left: "6.00%",
        backgroundColor:'transparent',
        opacity:"0.8",
        color:"white",
        paddingLeft: "12px",
        paddingRight: "18px",
        width:"210px",
        borderRadius:'22px',
    },
    textbox3:{
        position: "absolute",
        bottom:"6.0%",
        left: "76.00%",
        backgroundColor:'transparent',
        opacity:"0.8",
        color:"white",
        paddingLeft: "12px",
        paddingRight: "18px",
        width:"200px",
        borderRadius:'22px',
    },
    textbox4:{
        position: "absolute",
        bottom:"80.0%",
        left: "6.00%",
        backgroundColor:'transparent',
        opacity:"0.8",
        color:"white",
        paddingLeft: "12px",
        paddingRight: "18px",
        width:"200px",
        borderRadius:'22px',
    },
    textbox5:{
        position: "absolute",
        bottom:"80.0%",
        left: "75.00%",
        backgroundColor:'transparent',
        opacity:"0.8",
        color:"white",
        paddingLeft: "12px",
        paddingRight: "18px",
        width:"200px",
        borderRadius:'22px',
    },
    textbox6:{
        position: "absolute",
        bottom:"17.0%",
        left: "6.00%",
        backgroundColor:'transparent',
        opacity:"0.8",
        color:"white",
        paddingLeft: "12px",
        paddingRight: "18px",
        width:"210px",
        borderRadius:'22px',
    },
    textbox7:{
        position: "absolute",
        bottom:"17.0%",
        left: "74.00%",
        backgroundColor:'transparent',
        opacity:"0.8",
        color:"white",
        paddingLeft: "12px",
        paddingRight: "18px",
        width:"210px",
        borderRadius:'22px',
    },

}))